name: Selenium-Docker

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select the browser: chrome, firefox, edge, safari'
        type: string
        default: 'chrome'
        options:
          - 'chrome'
          - 'firefox'
          - 'safari'
      xmlfile:
        description: 'XML file to run the tests on'
        type: string
        default: 'testng.xml'
      runmode:
        description: 'Select the run mode: local, remote'
        type: string
        default: 'remote'
        options:
          - 'local'
          - 'remote'
      platform:
        description: 'Select the platform: seleniumgrid, lambdatest'
        type: string
        default: 'githubactions'

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Load Config and Merge Inputs
        run: |
          chmod +x ./set_env.sh
          ./set_env.sh
        env:
          INPUT_BROWSER: ${{ github.event.inputs.browser }}
          INPUT_XMLFILE: ${{ github.event.inputs.xmlfile }}
          INPUT_RUNMODE: ${{ github.event.inputs.runmode }}
          INPUT_PLATFORM: ${{ github.event.inputs.platform }}

      - name: Start Selenium Grid with Docker Compose
        if: ${{ env.PLATFORM == 'seleniumgrid' }}
        run: docker-compose -f docker/docker-compose-grid.yml up -d

      - name: Run Tests with Maven
        run: >
          mvn clean test 
          -Dsurefire.suiteXmlFiles=${{ env.XMLFILE }} 
          -Drunmode=${{ env.RUNMODE }} 
          -Dplatform=${{ env.PLATFORM }} 
          -Dbrowser=${{ env.BROWSER }}

      - name: Stop Selenium Grid with Docker Compose
        if: ${{ env.PLATFORM == 'seleniumgrid' }}
        run: docker-compose -f docker/docker-compose-grid.yml down

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: SparkHTML
          path: ./reports/*.html
